import { describe, expect, it } from 'vitest'
import type { Finding } from '../src/core/types.ts'
import { MARKDOWN_MARKER, code, prose, renderMarkdown } from '../src/report/markdown.ts'
import { asRemote, findingOf, recordedReport } from './report-fixtures.ts'

describe('Markdown report', () => {
  it('opens with the marker a bot finds its comment by, and a summary line', async () => {
    const markdown = renderMarkdown([(await recordedReport()).report])
    expect(markdown.startsWith(`${MARKDOWN_MARKER}\n## Rampa accessibility report\n`)).toBe(true)
    expect(markdown).toContain('**9 confirmed findings** on 1 page checked against WCAG 2.1 A/AA: 6 at Level A, 3 at Level AA.')
  })

  it('writes a finding as criterion and file:line, message, diff, evidence, confidence and id', async () => {
    const markdown = renderMarkdown([(await recordedReport()).report])
    expect(markdown).toContain(
      [
        '**[WCAG 2.4.4 (A)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html "Link Purpose (In Context)")** — `examples/store/before.html:31`\\',
        'The link text "Click here" does not tell where the link goes, and nothing around it does.',
        '',
        '```diff',
        '- <a href="shipping.html">Click here</a>',
        '+ <a href="shipping.html">Shipping information</a>',
        '```',
        'Evidence: "Click here" · confidence high · 1/1 runs · id `1af8a73e209d`',
      ].join('\n'),
    )
    // An engine finding shows the element and the rule instead of a diff.
    expect(markdown).toContain(
      '```html\n<img src="logo.svg" width="48" height="48" />\n```\nConfidence high · rule [image-alt](<https://dequeuniversity.com/rules/axe/4.14/image-alt?application=axeAPI>) (axe-core)',
    )
  })

  it('separates blocks by one blank line and keeps the blank lines inside code', async () => {
    const before = (await recordedReport()).report
    const after = (await recordedReport('examples-store-after')).report
    for (const markdown of [renderMarkdown([before]), renderMarkdown([before, after], { verbose: true }), renderMarkdown([after])]) {
      expect(markdown).not.toContain('\n\n\n')
    }
    const link = findingOf(before, '2.4.4')
    const spaced = { ...link, location: undefined, patch: link.patch && { ...link.patch, before: '<a>\n\nClick here</a>', after: '<a>\n\nShipping</a>' } }
    expect(renderMarkdown([{ ...before, findings: [spaced] }])).toContain('```diff\n  <a>\n  \n- Click here</a>\n+ Shipping</a>\n```')
  })

  it('folds what follows the fifth finding of a page into <details>', async () => {
    const markdown = renderMarkdown([(await recordedReport()).report])
    const folded = markdown.slice(markdown.indexOf('<details>'))
    expect(folded.startsWith('<details>\n<summary>4 more findings on this page</summary>\n\n**[WCAG 2.4.4 (A)]')).toBe(true)
  })

  it('ends with the coverage statement, how to waive a false positive and the tools', async () => {
    const markdown = renderMarkdown([(await recordedReport()).report])
    const coverage = markdown.indexOf('#### Coverage of this run')
    expect(coverage).toBeGreaterThan(markdown.lastIndexOf('id `'))
    expect(markdown).toContain('- Not checked automatically: 38 of 50 WCAG 2.1 A/AA criteria')
    expect(markdown).toContain('**This report does not declare the page accessible.** What was not checked needs manual review and testing with people.')
    expect(markdown).toContain('<summary>False positive? Waive it</summary>')
    expect(markdown).toContain('"fingerprint": "5f085d8a3b9c"')
    expect(markdown.trimEnd().endsWith('<sub>Generated by [Rampa](https://rampa.guilhermebs.com.br) 0.0.0 · axe-core 4.14.0 · ollama:gemma4:12b</sub>')).toBe(true)
  })

  it('still states the coverage when nothing was found', async () => {
    const markdown = renderMarkdown([(await recordedReport('examples-store-after')).report])
    expect(markdown).toContain('**No confirmed failures in what was checked on 1 page.**')
    expect(markdown).toContain('#### Coverage of this run')
    expect(markdown).not.toContain('False positive?')
  })

  it('reports several pages with a table of coverage and a line for the clean ones', async () => {
    const before = (await recordedReport()).report
    const after = (await recordedReport('examples-store-after')).report
    const markdown = renderMarkdown([before, after])
    expect(markdown).toContain('**9 confirmed findings** on 2 pages checked against WCAG 2.1 A/AA')
    expect(markdown).toContain('No confirmed failures in what was checked on 1 more page: `examples/store/after.html`')
    expect(markdown).toContain('| Page | Checked by axe-core (partial) | Judged with verified evidence | Not checked automatically |')
    expect(markdown).toContain('| `examples/store/after.html` |')
  })

  it('uses the selector where there is no file, as for a remote page', async () => {
    const markdown = renderMarkdown([asRemote((await recordedReport()).report)])
    expect(markdown).toContain('### `https://shop.example/new`')
    expect(markdown).toContain('— `html > body > main > p:nth-of-type(2) > a`\\')
    expect(markdown).toContain('- <a href="shipping.html">Click here</a>')
  })

  it('speaks Portuguese with --locale pt-BR', async () => {
    const markdown = renderMarkdown([(await recordedReport('examples-store-before', { locale: 'pt-BR' })).report])
    expect(markdown).toContain('## Relatório de acessibilidade do Rampa')
    expect(markdown).toContain('**9 achados confirmados** em 1 página verificada contra a WCAG 2.1 A/AA: 6 de nível A, 3 de nível AA.')
    expect(markdown).toContain('O texto do link "Click here" não diz para onde o link leva, e nada ao redor diz.')
    expect(markdown).toContain('Evidência: "Click here" · confiança alta · 1/1 rodadas')
    expect(markdown).toContain('<summary>mais 4 achados nesta página</summary>')
    expect(markdown).toContain('**Este relatório não declara a página acessível.**')
    expect(markdown).toContain('<summary>Falso positivo? Dispense o achado</summary>')
  })

  it('makes text from the page inert: no mentions, references, HTML or broken code', async () => {
    expect(prose('Follow @octocat, see #12 and <b>*bold*</b> | a_b')).toBe(
      'Follow @&#8203;octocat, see #&#8203;12 and \\<b\\>\\*bold\\*\\</b\\> \\| a\\_b',
    )
    expect(prose('Tom &amp; Jerry\nnext line')).toBe('Tom &amp;amp; Jerry next line')
    expect(code('a `b` c')).toBe('``a `b` c``')
    expect(code('`edge`')).toBe('`` `edge` ``')
    const { report } = await recordedReport()
    const link = findingOf(report, '2.4.4')
    const hostile: Finding = { ...link, message: 'The link text "@admin <img src=x onerror=alert(1)>" says nothing.', evidence: '@admin ```' }
    const markdown = renderMarkdown([{ ...report, findings: [hostile] }])
    expect(markdown).not.toMatch(/@admin/)
    // Escaped, the tag renders as text.
    expect(markdown).not.toMatch(/(?<!\\)<img src=x/)
    expect(markdown).toContain('\\<img src=x onerror=alert(1)\\>')
    expect(markdown).toContain('Evidence: "@&#8203;admin \\`\\`\\`"')
  })

  it('links an engine rule only to an http(s) address, since the page could plant another', async () => {
    const { report } = await recordedReport()
    const engine = report.findings[0] as Finding
    const planted = renderMarkdown([{ ...report, findings: [{ ...engine, helpUrl: 'javascript:alert(1)' }] }])
    expect(planted).not.toContain('javascript:')
    expect(planted).toContain('rule `image-alt` (axe-core)')
  })

  it('stays under the size limit of a GitHub comment and says what it left out', async () => {
    const { report } = await recordedReport()
    const many = Array.from({ length: 600 }, (_, index) => report.findings.map((finding) => ({ ...finding, fingerprint: `${finding.fingerprint}-${index}` }))).flat()
    const markdown = renderMarkdown([{ ...report, findings: many }])
    expect(markdown.length).toBeLessThanOrEqual(60_000)
    expect(markdown).toMatch(/> \d+ findings were left out to fit the size limit of a comment/)
    expect(markdown).toContain('#### Coverage of this run')
    expect(renderMarkdown([{ ...report, findings: many }], { maxLength: 5000 }).length).toBeLessThanOrEqual(5000)
  })

  it('fits a site of hundreds of pages, findings and closing statement included', async () => {
    const before = (await recordedReport()).report
    const after = (await recordedReport('examples-store-after')).report
    const clean = Array.from({ length: 300 }, (_, index) => ({ ...after, target: `site/page-${index}.html`, sourceFile: `site/page-${index}.html` }))
    const markdown = renderMarkdown([before, ...clean])
    expect(markdown.length).toBeLessThanOrEqual(60_000)
    expect(markdown).toContain('`examples/store/before.html:31`')
    expect(markdown).not.toContain('left out to fit')
    expect(markdown).toContain('- …and 280 more')
    expect(markdown).toContain('**This report does not declare the page accessible.**')
    expect(markdown.trimEnd().endsWith('</sub>')).toBe(true)
  })

  it('keeps any line break and issue shorthand in page text inert', () => {
    expect(prose('x\r# Heading')).toBe('x # Heading')
    expect(prose('see GH-12')).toBe('see GH-&#8203;12')
  })
})
