"""Builds the word lists the letter-spaced words rule reads (src/rules/words/*.ts).

Rampa's rule rampa/letter-spaced-words (WCAG 1.3.2, F32) joins letters written with spaces between
them ("W E L C O M E") and asks whether they make a word in the element's language. It needs a word
list per language that ships with Rampa: small, offline, and free to redistribute. Hunspell
dictionaries are too large to ship and list stems, not the forms people write ("ofertas", "notícias").

Source: the sentences of Tatoeba (https://tatoeba.org), per-language exports, licensed CC BY 2.0 FR
(some sentences CC0 1.0). The lists hold only words and their frequency rank, never sentences.

For each language the script counts word forms in every sentence, then keeps the forms that:
- are 4 to 15 Latin letters (accents included), since the rule needs four letters or more;
- occur at least MIN_COUNT times, which drops typos and rare names;
- are written in lower case in most of their uses after the start of a sentence, which drops names
  and acronyms (Tom, Brasil, NASA, ASAP);
and writes the TOP most frequent, plus the few words in SEED, which a web page often writes with
letter spacing ("menu", "sale", "contato", "bienvenidos").

Usage (Python 3, standard library only):
    python -I scripts/word-lists.py <download dir> <output dir>
The download dir keeps the exports between runs; the output dir is src/rules/words.
"""

import bz2
import hashlib
import os
import re
import sys
import unicodedata
import urllib.request
from collections import Counter

LANGUAGES = {
    # Rampa language: (Tatoeba code, how many words to keep)
    'en': ('eng', 20000),
    'pt': ('por', 20000),
    'es': ('spa', 20000),
}
MIN_COUNT = 5
MIN_LOWER_SHARE = 0.6
URL = 'https://downloads.tatoeba.org/exports/per_language/{code}/{code}_sentences.tsv.bz2'

# Words pages write in capitals with spaces for the look: headings, banners, menus. Written for Rampa (MIT).
SEED = {
    'en': 'menu home about news sale shop store blog contact welcome login search cart account offers events gallery team services products portfolio',
    'pt': 'menu início sobre notícias ofertas promoção promoções loja contato contatos serviços produtos equipe galeria eventos entrar carrinho conta bem vindo',
    'es': 'menú inicio noticias ofertas tienda contacto servicios productos equipo galería eventos entrar carrito cuenta bienvenidos bienvenido',
}

WORD = re.compile(r"[^\W\d_]+", re.UNICODE)
LATIN = re.compile(r"^[a-zà-öø-ÿāăąćĉċčďđēĕėęěĝğġģĥħĩīĭįıĵķĺļľŀłńņňŉōŏőœŕŗřśŝşšţťŧũūŭůűųŵŷźżž]+$")


def fetch(code: str, folder: str) -> str:
    path = os.path.join(folder, f'{code}_sentences.tsv.bz2')
    if not os.path.exists(path):
        os.makedirs(folder, exist_ok=True)
        with urllib.request.urlopen(URL.format(code=code), timeout=120) as response, open(path, 'wb') as out:
            out.write(response.read())
    return path


def count(path: str) -> tuple[Counter, Counter, Counter, int]:
    total, later, lower = Counter(), Counter(), Counter()
    sentences = 0
    with bz2.open(path, 'rt', encoding='utf-8') as lines:
        for line in lines:
            parts = line.rstrip('\n').split('\t')
            if len(parts) < 3:
                continue
            sentences += 1
            text = unicodedata.normalize('NFC', parts[2])
            for index, match in enumerate(WORD.finditer(text)):
                form = match.group(0)
                key = form.lower()
                total[key] += 1
                if index == 0:
                    continue
                later[key] += 1
                if form == key:
                    lower[key] += 1
    return total, later, lower, sentences


def keep(key: str, total: Counter, later: Counter, lower: Counter) -> bool:
    if not 4 <= len(key) <= 15 or not LATIN.match(key):
        return False
    if total[key] < MIN_COUNT:
        return False
    # Mostly lower case where case is free: not a name or an acronym.
    return later[key] > 0 and lower[key] / later[key] >= MIN_LOWER_SHARE


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    downloads, output = sys.argv[1], sys.argv[2]
    os.makedirs(output, exist_ok=True)
    for language, (code, top) in LANGUAGES.items():
        path = fetch(code, downloads)
        with open(path, 'rb') as file:
            digest = hashlib.sha256(file.read()).hexdigest()
        total, later, lower, sentences = count(path)
        ranked = [key for key, _ in total.most_common() if keep(key, total, later, lower)][:top]
        seed = [unicodedata.normalize('NFC', word) for word in SEED[language].split() if len(word) >= 4]
        words = sorted(set(ranked) | set(seed))
        name = f'WORDS_{language.upper()}'
        header = (
            f'// Generated by scripts/word-lists.py; do not edit by hand.\n'
            f'// {len(words)} words: the {len(ranked)} most frequent forms of 4 to 15 letters in the {sentences} sentences of\n'
            f"// Tatoeba's {code} export ({os.path.basename(path)}, SHA-256 {digest[:16]}…), mostly written in lower case,\n"
            f'// plus {len(seed)} words pages often letter-space. Source: https://tatoeba.org, CC BY 2.0 FR\n'
            f'// (https://creativecommons.org/licenses/by/2.0/fr/); the list holds words and no sentences.\n'
        )
        body = '\n'.join(words)
        with open(os.path.join(output, f'{language}.ts'), 'w', encoding='utf-8', newline='\n') as out:
            out.write(header)
            out.write(f'export const {name} = `{body}`\n')
        print(f'{language}: {len(words)} words from {sentences} sentences; {digest}')


if __name__ == '__main__':
    main()
