export { check, type CheckTargetsOptions } from './api/check.ts'
export type { RampaOptions } from './api/options.ts'
export { type AssertOptions, formatFindings } from './testing/format.ts'
export { assertRampa } from './testing/matchers.ts'
export { defineConfig, loadConfig, loadWaivers, type RampaConfig } from './config.ts'
export {
  compareWithBaseline,
  readBaseline,
  recordBaseline,
  writeBaseline,
  type BaselineComparison,
  type BaselineEntry,
  type BaselineFile,
} from './adoption/baseline.ts'
export { activeFingerprints, readWaivers, upsertWaiver, writeWaivers, type Waiver, type WaiverFile } from './adoption/waivers.ts'
export { fileCache, memoryCache, type JudgmentCache } from './core/cache.ts'
export { checkSnapshot, engineFindings, type CheckOptions } from './core/check.ts'
export { judgeCandidates, majority } from './core/judge.ts'
export type { RepeatedFinding, SiteReport, SiteSummary } from './core/site.ts'
export type { PageSet, SiteCriteriaReport, SiteCriterion, SiteFinding, SitePageFacts } from './core/site.ts'
export { SITE_CRITERIA, type SiteCriteriaOptions, type SitePageRecord, runSiteCriteria, siteFactsOf } from './site/index.ts'
export type * from './core/types.ts'
export { CRITERIA, DEFAULT_CRITERIA, resolveCriteria } from './criteria/index.ts'
export { languageOfParts } from './criteria/language-of-parts.ts'
export { isGenericAlt, looksLikePlaceholder, nonTextContent } from './criteria/non-text-content.ts'
export { engineFromAxe } from './engine/axe.ts'
export { runRules } from './engine/rules.ts'
export { REASONING_LEVELS, type Reasoning, createModelProvider, parseModelSpec } from './providers/ai-sdk.ts'
export { PROVIDERS, type ProviderDef, findProvider } from './providers/registry.ts'
export type { JudgeRequest, JudgeResponse, ModelProvider } from './providers/types.ts'
export { FAIL_ON, type FailOn, exitCode, failingFindings } from './cli/exit-code.ts'
export { FORMATS, type Format, formatReports } from './report/formats.ts'
export { type HtmlOptions, renderHtml } from './report/html.ts'
export { MARKDOWN_MARKER, type MarkdownOptions, renderMarkdown } from './report/markdown.ts'
export { type SarifLog, type SarifOptions, toSarif } from './report/sarif.ts'
export { type PageSource, locateReport, readPageSource, repositoryRoot } from './source/locate.ts'
export { A11yNodeSchema, A11ySnapshotSchema, SURFACES, type A11yNode, type A11ySnapshot, type Surface } from './snapshot/schema.ts'
export { type BrowserOptions, parseBrowserFlags } from './surfaces/browser-options.ts'
export { collectWeb, launchBrowser } from './surfaces/web.ts'
export { type AdbRunner, collectAndroid } from './surfaces/android/adb.ts'
export { snapshotFromUiAutomator } from './surfaces/android/uiautomator.ts'
export { collectImage } from './surfaces/image.ts'
export { importXcuitest, isXcuitestExport } from './surfaces/ios.ts'
export { loadSnapshot, resolveTargets } from './surfaces/targets.ts'
export { VERSION } from './version.ts'
