export { check, type CheckTargetsOptions } from './api/check.ts'
export type { RampaOptions } from './api/options.ts'
export { defineConfig, loadConfig, type RampaConfig } from './config.ts'
export { fileCache, memoryCache, type JudgmentCache } from './core/cache.ts'
export { checkSnapshot, engineFindings, type CheckOptions } from './core/check.ts'
export { judgeCandidates, majority } from './core/judge.ts'
export type * from './core/types.ts'
export { CRITERIA, DEFAULT_CRITERIA, resolveCriteria } from './criteria/index.ts'
export { languageOfParts } from './criteria/language-of-parts.ts'
export { isGenericAlt, looksLikePlaceholder, nonTextContent } from './criteria/non-text-content.ts'
export { engineFromAxe } from './engine/axe.ts'
export { REASONING_LEVELS, type Reasoning, createModelProvider, parseModelSpec } from './providers/ai-sdk.ts'
export { PROVIDERS, type ProviderDef, findProvider } from './providers/registry.ts'
export type { JudgeRequest, JudgeResponse, ModelProvider } from './providers/types.ts'
export { A11yNodeSchema, A11ySnapshotSchema, SURFACES, type A11yNode, type A11ySnapshot, type Surface } from './snapshot/schema.ts'
export { collectWeb, launchBrowser } from './surfaces/web.ts'
export { loadSnapshot, resolveTargets } from './surfaces/targets.ts'
export { VERSION } from './version.ts'
